// <auto-generated />
namespace SimpleSheduler.BD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class DelStudyDayNumWeek21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DelStudyDayNumWeek21));
        
        string IMigrationMetadata.Id
        {
            get { return "201910072030365_DelStudyDayNumWeek21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
