//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curricula
    {
        public int CurriculumId { get; set; }
        public int GroupId { get; set; }
        public int SubjectId { get; set; }
        public int Number { get; set; }
        public int TypeOfClassesId { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual TypeOfClasses TypeOfClasses { get; set; }
    }
}
