//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanToTwoWeek
    {
        public int PlanID { get; set; }
        public int GroupID { get; set; }
        public int SubjectID { get; set; }
        public Nullable<int> NumPract { get; set; }
        public Nullable<int> NumLec { get; set; }
        public Nullable<int> NumLab { get; set; }
    }
}
