//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shedulers
    {
        public int ShedulerId { get; set; }
        public int NumberWeek { get; set; }
        public string DayWeek { get; set; }
        public int NumberPair { get; set; }
        public int ClassroomId { get; set; }
        public int SubjectId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Classrooms Classrooms { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
