//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int PlanID { get; set; }
        public string FullName { get; set; }
        public int NumberOfPersons { get; set; }
        public string Seminar { get; set; }
        public string Potok { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> NumPract { get; set; }
        public Nullable<int> NumLec { get; set; }
        public Nullable<int> NumLab { get; set; }
    }
}
